BUG: Missing itkMath.h include
Without this patch, the following error happens:

include/itkDigitizerFunctor.h:79:16: error: use of undeclared identifier 'Math'
     return Math::Floor< TOutput >((inputPixel - m_Min)/((m_Max-m_Min)/ \
         (float)m_NumberOfBinsPerAxis));