COMP: Add missing NumericTraits header to itkDigitizerFunctor
Addresses:

  /home/matt/src/ITKTextureFeatures/include/itkDigitizerFunctor.h:36:13: error:
  use of undeclared identifier 'NumericTraits'
        m_Min(NumericTraits<PixelType>::min()),